name: setup-node
description: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/.pnpm-store
          **/node_modules/.pnpm
        key: pnpm-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies 🔧
      shell: bash
      run: pnpm install
